### ISSUE TITLE
Using a fragment of type query, the `Unknown field 'xxx' on type 'Query'` and an error response will be returned

### ISSUE THREAD

**Issue by mayone-du** [supabase/pg_graphql#273]
**Describe the bug**
See the following code.

```
fragment Post on Posts {
  id
}

fragment PostList on Query {
  postsCollection(first: $first, filter: $filter) {
    edges {
      node {
        ...Post
      }
    }
  }
}

query PostsPage($filter: PostsFilter!, $first: Int = 100) {
  ...PostList
}
```

If you run a query like this
`Unknown field 'PostList' on type 'Query'`
and an error response will be returned at runtime.

The graphql-code-generator works fine, and I believe the query being executed is also normal.

It worked for inline fragments.

**To Reproduce**
1.Execute a fragment, query as in the example
2.Check response from console

**Expected behavior**
Operate normally

**Screenshots**

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - pg_graphql commit ref: ea2ab60

**Additional context**

**Comment by olirice** [comment]
ea2ab60b1f80c3be92c0d1f8453ef0bbec0b7f55 is from before the `v0.1.0` and is very out of date at this point. Are you sure that was correct?

There was an issue with inline fragments as recently as last week. It was resolved in (unreleased on supabase platform at time of writing) `v0.5.3`.

Here is a full reproducible example that uses your snippet on master:

```sql
    create table posts(
        id int primary key,
        title text not null
    );

    insert into posts(id, title) values (1, 'asdf');

    select graphql.resolve($$
fragment Post on Posts {
  id
}

fragment PostList on Query {
  postsCollection(first: $first, filter: $filter) {
    edges {
      node {
        ...Post
      }
    }
  }
}

query PostsPage($filter: PostsFilter!, $first: Int = 100) {
  ...PostList
}
    $$);
```
Output
```
                             resolve                             
-----------------------------------------------------------------
 {"data": {"postsCollection": {"edges": [{"node": {"id": 1}}]}}}
(1 row)
```

If you're using the supabase platform and send your project_ref I can get your project updated so you can start using ^ now


refs:
dupe of #268

**Comment by kav** [comment]
Can confirm this is the same issue. `Unknown field 'xxx' on type 'Query'` where xxx is the fragment name was the error I saw on v0.4

**Comment by mayone-du** [comment]
@olirice 
Thank you! I think the commit history is wrong. I forgot to edit it. My apologies.

This problem is happening in local development, how can I fix it?
Deleting and re-pulling the Docker image did not solve the problem.

**Comment by olirice** [comment]
@mayone-du v0.5.3 hasn't been pushed to the `supabase/postgres:latest` docker image yet so unfortunately that fix won't be available for local development until then. Looking at the release schedule it should trickle down to the CLI by end of next week, sorry for the delay

**Comment by olirice** [comment]
Which docker image tag do you have?

For the latest version of pg_graphql it should be
`supabase/postgres:15.1.0.14` for pg15 or `supabase/postgres:14.1.0.105` for pg14

**Comment by mayone-du** [comment]
Oops, looks like it was `supabase/postgres:14.1.0.89 `. Sorry.

How do I install `supabase/postgres:15.1.0.14` or `supabase/postgres:14.1.0.105`?

**Comment by olirice** [comment]
it depends how you're local environment is set up

If you're using the supabase CLI you'll want to upgrade to the latest version `brew upgrade supabase` (assuming Mac) but the latest docker image can take a few weeks to trickle down to the CLI. We cautious about updating the version used by the CLI because offline setups tend to have a longer lifespan and are harder to update when issues occur

If you're using docker-compose you need to update the `docker-compose.yml` `image` tag

or if you're using docker directly, replace the tag in your command
